name = "gentechlabs-site"
compatibility_date = "2024-01-01"
account_id = "a618b777aff85c5360bd847629385b4d"
main = "src/gentechlabs-site.ts"

[vars]
ENVIRONMENT = "production"
VPS_IP = "2.24.195.196"
VPS_PORT = "80"
