name = "gentech-x402-testnet"
main = "worker.js"
compatibility_date = "2025-06-01"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"

[vars]
WALLET_ADDRESS = "0x7ebff188f2Eba16518C02864589b1403a5d1296a"
TESTNET_MODE = "1"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "de2f4543ecef44d191fc617024473c99"
